[package]
name = "integrate"
version = "0.1.0"
authors = ["Mr-Andersen <andrew-anderson.neo@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.3"

[profile.release]
lto = 'fat'
codegen-units = 1
